### ISSUE TITLE
Do you inialize your designed network with the pretrained weights?

### ISSUE THREAD

**Issue by CrystalSixone** [YushengZhao/TD-STP#2]
Hi, Dear YuSheng! 
Thanks for your amazing work. I am interested in your work and I'm doing some research based on the VLN-HAMT as well. I am wondering if you initialize your designed network by using `model_step_22000.pt` provided by HAMT? And if so, did you do experiments directly on the fine-tune stage?
It would be my great pleasure if you could reply to me. Thank you again. 
Best wishes. 
:)

**Comment by YushengZhao** [comment]
Yes, we use the pretrained weights of HAMT as initialization in our experiments.
